[project]
name = "service-ask-marc"
version = "0.1.0"
description = "A bridge for OpenRemote to communicate with AI models like ChatGPT or Claude. And provide configuration to connect them to tools using MCP."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "shared",
    "mcp-server",
    "mcp-client-api",
]

[tool.uv.sources]
shared = { workspace = true }
mcp-server = { workspace = true }
mcp-client-api = { workspace = true }

[tool.uv.workspace]
members = [
    "src/shared",
    "src/services/mcp-server",
    "src/services/mcp-client-api"
]