/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    MessageView: typeof import('./components/MessageView.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    PromptBox: typeof import('./components/PromptBox.vue')['default']
  }
}
